version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/_stcore/health | grep -q 'ok' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

